version: "2.3"

services:
  backend:
    runtime: nvidia
    image: tornermarton/system-monitor-backend:latest
    container_name: system-monitor-backend
    tty: true
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "3000:3000"

  frontend:
    image: tornermarton/system-monitor-frontend:latest
    container_name: system-monitor-frontend
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./config.json:/usr/share/nginx/html/assets/config.json"
